python index_builder.py ^
    --retrieval_method bge ^
    --model_path ^
    --corpus_path  ^
    --save_dir  ^
    --use_fp16 ^
    --max_length 512 ^
    --batch_size 256 ^
    --pooling_method mean ^
    --sentence_transformer ^
    --faiss_type Flat
